/**
 * The founder board's content — HammerTrack's own operating picture.
 *
 * Brian, Aug 28: "I want all of my Hammertrack items combined... to do list
 * road map financials, all of it. it feels Scattered and needs to have one
 * home for everything."
 *
 * This is that one home's SOURCE. Live numbers (devices reporting, assets on
 * the map) are read from the database by the page; everything here is the
 * standing picture that only changes when a decision changes.
 *
 * ── Where this fits the sync rule ──────────────────────────────────────
 * The repo already requires that any roadmap / to-do / cost change updates
 * marketing/system-map.html and the cost docs in the SAME commit. This file
 * joins that set: it is the single place the board reads from, so a change
 * here plus the graphic plus the docs keeps all three honest. Numbers here
 * are transcriptions of docs/ — if they ever disagree, the docs win.
 */

export type Owner = 'brian' | 'build'
export type TaskState = 'open' | 'flight' | 'done'
export type Severity = 'stop' | 'warn' | 'none'

export interface BoardTask {
  id: number
  title: string
  /** Why it matters / what it unblocks. Shown under the title while open. */
  why?: string
  owner: Owner
  state: TaskState
  sev?: Severity
}

/** Board ids are stable handles ("board #66") — new items take the next free
 *  number; ids are never reused. Refreshed against reality 1 Sep 2026. */
export const TASKS: BoardTask[] = [
  // ── Yours, blocking ──────────────────────────────────────────────────
  { id: 46, title: 'Pay the declined KORE invoice', why: 'Card declined 18 Aug on the 14 Aug invoice. An account in arrears can suspend the 13 SuperSIMs activating now — pay it from the Mercury KORE virtual card. Invoice number is in the AR email. Mark done when paid.', owner: 'brian', state: 'open', sev: 'stop' },
  { id: 66, title: 'Google Ads account is PAUSED — finish advertiser verification', why: 'Google paused the ads account 31 Aug because the verification tasks were not completed by the deadline. Nothing runs until it clears: Google Ads → Billing → Advertiser verification (business questions plus the EIN letter or SC LLC registration). The theft-hook funnel cannot spend until then.', owner: 'brian', state: 'open', sev: 'stop' },
  { id: 40, title: 'T1-b OBD unit (…00200) pulled from the 2500HD — a TAT141 tracks the truck now', why: 'Sep 10: the OBD port on the 2003 Silverado would not power the unit no matter what, so Brian put a TAT141 on the truck instead. The …00200 OBD box is spare — file it in the Unassigned drawer on /trackers (Take out on the machine page if it is still attached) and reuse it on a newer truck; its Hologram SIM stays paused-free until then.', owner: 'brian', state: 'done' },

  // ── Yours, soon ──────────────────────────────────────────────────────
  { id: 119, title: 'Play: the Foreground service declaration — DONE, 1.4.1 is rolling out', why: 'You filed it at 3:14 AM (type Location → user-initiated location sharing) and Play took it for review. The release itself was still parked as a draft, so it was started from here — same build, nothing rebuilt — and the production track now reads 1.4.1. Crew phones get the shift recorder that keeps working with the screen off as Play finishes its review and the update reaches them. Two tools came out of the night so this never costs you an hour again: one reads the console state directly (no more tabbing between tabs to tell me what you see), the other starts a parked release without a rebuild.', owner: 'brian', state: 'done' },
  { id: 124, title: 'Label the fleet by division', why: 'Divisions shipped Sep 11 (Settings → Divisions). Create Upstate and Coastal, then label the trucks and job sites — the asset page and zone page each have a Division card, and the map, assets list and zones list all gain a filter once at least one division exists. Nothing else changes until you do: every row starts unassigned.', owner: 'brian', state: 'open' },
  { id: 122, title: 'Stop the deploy-bot emails (two Vercel projects + the dead Netlify site)', why: 'GitHub emails you every bot comment on a PR you authored, and three robots comment on every one: Vercel for hammertrackjune28 (the live site), Vercel for a DUPLICATE project called hello-world on the same team (a second full build of every push — it can even run the migration step twice), and Netlify for stately-heliotrope-0b2bff, the dead site from before Vercel. Fix in three clicks: (1) vercel.com → hammertrack-team → hello-world → Settings → Domains: if only *.vercel.app is listed, delete the project (Settings → Advanced); (2) hammertrackjune28 → Settings → Git → Comments → turn off Pull request comments; (3) app.netlify.com → stately-heliotrope-0b2bff → Project configuration → General → Delete project (or Notifications → remove the deploy-preview comments). Until then a Gmail filter on from:notifications@github.com with “[bot]” → skip inbox.', owner: 'brian', state: 'open' },
  { id: 101, title: 'Glance at the Supabase Disk IO graph in a couple of days', why: 'Supabase warned on 3 Sep that the database was burning through its Disk IO budget (slow responses, possible unresponsiveness). Cause found and fixed the same night (migration 087): the hourly hours-ledger rebuild re-read up to 60 days of GPS pings per zone every hour. Nothing to do now — open the project’s Reports → Disk IO once after 5 Sep. Flat and low = done. Still climbing = upgrade compute Micro → Small ($15/mo) in Project Settings → Compute, and tell me.', owner: 'brian', state: 'open' },
  { id: 102, title: 'Customer #2: sister paving company in Charleston — get the owner registered', why: 'Sep 9: two OBD units (…33818, …48247), a TAT141 (…4734) and three Eye Beacons (…B56B, …B573, …B521) went with him. They are OFF the DCG placeholders and in DCG’s drawer. He registers at hammertrack.ai/register (company name = his company; that makes him the Master), tells you the email, and the six devices + assets move into his account in minutes — no rescans. If he beats us to it: Trackers → Add trackers (scan) → Put on a machine works for him too (docs/CUSTOMER-SETUP.md). Founding-25 terms apply.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 99, title: 'Optional: free CARTO basemaps key for the retina look', why: 'CARTO now requires a key, so the map moved to Esri’s keyless canvas basemaps on 2 Sep — no more “API KEY REQUIRED” stamps. CARTO’s tiles are sharper on phones and stay crisp zoomed into a yard; the free Esri fallback blurs past zoom 16. If you want them back: carto.com/basemaps/apikey (email + domain hammertrack.ai, one minute, no account) → NEXT_PUBLIC_CARTO_KEY in Vercel → redeploy. Free to 5M tiles a month.', owner: 'brian', state: 'open' },
  { id: 81, title: 'Fix www.hammertrack.ai — visitors get a browser warning', why: 'The certificate served for www only covers the apex, so anyone typing www sees a security warning page. Vercel → project → Settings → Domains → add www.hammertrack.ai as a redirect to hammertrack.ai; the certificate issues itself. hammertrackai.com has no www record at all — add one there too.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 41, title: 'Apple: Individual enrollment SUBMITTED Sep 10 — watch the DCG inbox for the welcome email', why: 'Apple denied the HAMMERTRACK LLC organization enrollment by phone (Sep 4, case 20000149520723) but never closed it — it still reads “In Review”, so brian@hammertrack.ai could not enroll again and the iPad app route failed. Sep 10: enrolled as an INDIVIDUAL on the PC under a new Apple ID, brian@dillardconstructiongroup.com ($99). Watch THAT inbox: “Welcome to the Apple Developer Program” (minutes to ~48 h); an identity-verification request first is normal — answer it. Optional: developer.apple.com/contact → Program Enrollment → ask Apple to withdraw N37H75H2FX in writing. Approval day (~15 min): App Store Connect → Users and Access → Integrations → generate a TEAM API key with the Admin role, download the .p8 once, copy the Key ID + Issuer ID, read the Team ID from Membership → four GitHub secrets (ASC_KEY_ID, ASC_ISSUER_ID, ASC_KEY_P8, ASC_TEAM_ID) → say “apple secrets are in” and the ios-testflight workflow builds on GitHub’s Macs and lands in TestFlight the same hour. Everything else is ready as of Sep 10: signing, 1.4.1, permission strings, review notes, demo account, in-app login. Runbook: docs/APP-STORE-PLAYBOOK.md → Approval day.', owner: 'brian', state: 'flight', sev: 'warn' },
  { id: 68, title: 'Check the Twilio toll-free verdict', why: '“In review” is a month old and no verdict email exists anywhere. Twilio console → Regulatory Compliance → Toll-Free Verification. Approved: SMS theft alerts go live and the text claims go back on the splash. Rejected: fix the use-case description and resubmit. The splash was softened to “alert on your phone” on 1 Sep so nothing is claimed that has not delivered.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 43, title: 'Answer KORE: onboarding call + order #2 asks', why: 'Claire (KORE customer success) asked 26 Aug for a time for the onboarding call — unanswered. Reply with a slot, and keep the asks only KORE can answer: the skipped pre-configuration, the 14-devices-to-13-SIMs gap, order #2 pre-config and lead time. docs/TELTONIKA-DEVICES.md already settled the gateway and camera questions.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 45, title: 'Push the real config to every FMM00A (FOTA)', why: 'One FOTA WEB push to all five trucks: enable Green Driving IO (harsh accel/brake for driver grades) and the fast reporting profile — the default 5–15 minute intervals are why some trucks draw straight dashed chords instead of roads.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 1, title: 'QuickBooks connect — 45 minutes', why: 'docs/QBO-GO-LIVE.md is the click-by-click: create the Intuit app, paste four QBO_ vars into Vercel, redeploy, connect from /accounting. Until then the splash, /demo and /pricing label QuickBooks as coming (softened 1 Sep). Connecting flips them back.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 67, title: 'Hire S1 — the model says this month', why: 'The operating model fires S1 in Sep 2026 at zero customers because founder hours are the constraint. One-paragraph job: rolodex hire, $800 base + $200 per activated account, 60-day kill rule. Put it in front of two or three Upstate names.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 83, title: 'Confirm the Play app is registered for developer verification (by 30 Sep)', why: 'Google Play’s final reminder (31 Aug): every Play app must be registered by 30 Sep 2026 or it is removed. Over 99% were auto-registered — open the Play Console home page and confirm com.hammertrack.app reads “registered”. Two minutes.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 87, title: 'Decide: private home for the prospect list + hardware pricing', why: 'docs/FOUNDING-25.md carried 25 named prospects with personal emails and phones in the public repo; the contact details were redacted 1 Sep but live on in git history. docs/HARDWARE-PRICING.md is labelled confidential and is public too. Move both to Drive and say whether you want the history scrubbed (a force-push everyone re-clones from).', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 65, title: 'Re-upload the Play listing assets', why: 'The live listing still shows raw browser screenshots and no tagline. Paste the short description from docs/APP-STORE-LISTING.md, replace the phone screenshots with store-assets/android-phone/*.png, add the feature graphic, and write the v1.2 What’s New.', owner: 'brian', state: 'open' },
  { id: 70, title: 'Bring the rest of KORE order #1 online', why: 'Five of six OBD units came up 28 Aug. The six TAT141s, three FMM650s, ten Eye Beacons and the last pairing puck still need SIM → FOTA config → scan. /assets/onboard shows each device’s first unfinished step.', owner: 'brian', state: 'open' },
  { id: 71, title: 'Cost rates on the big iron', why: 'Burn Map, Idle $ rings, the insights engine and the owner memo all read $/hr and $/day per machine — without rates on the big iron they tell half a story. The advise-from-specs button gives a starting number.', owner: 'brian', state: 'open' },
  { id: 69, title: 'Turn on the receipt chase (Resend inbound)', why: 'Built 1 Aug, dark since. Resend → enable inbound on hammertrack.ai → webhook to /api/inbound/receipts → whsec_ secret into Vercel as RESEND_INBOUND_SECRET → redeploy → Enable on /receipts, map card last-4s, point the bank’s per-swipe alerts at the inbound address.', owner: 'brian', state: 'open' },
  { id: 72, title: 'Seed the showroom company', why: 'S1 demos on it and /model expects it. docs/SHOWROOM.md: create a fresh account, then /model → Showroom company → Seed. Until then the only demo is the mock stage or DCG’s live books.', owner: 'brian', state: 'open' },
  { id: 84, title: 'Supabase: rerun the security linter', why: 'The advisor flagged two public tables without row-level security (the deploy ledger and the PostGIS reference table). Migration 086 locked the ledger down 1 Sep. Dashboard → Advisors → Security → Rerun linter: the ledger row should be gone; if spatial_ref_sys is the ONLY critical row left, that is expected (owned by the extension — board #98 moves PostGIS out of public). Anything else, send the table name.', owner: 'brian', state: 'open' },
  { id: 85, title: 'One GitHub secret left: CRON_SECRET', why: 'Repo → Settings → Secrets → Actions → CRON_SECRET (Vercel’s value). Lets the daily diag probe read production health again — it has printed “unauthorized” since 26 Aug. (PLAY_SERVICE_ACCOUNT_JSON is in and proven, 3 Sep.)', owner: 'brian', state: 'open' },
  { id: 86, title: 'Turn on Vercel Web Analytics', why: 'The marketing site had no analytics at all — the ad funnel was unmeasured. Two clicks in one sitting: Vercel → project → Analytics → Enable, then add NEXT_PUBLIC_VERCEL_ANALYTICS=1 to the project env and redeploy (the component stays off until then so production consoles stay clean). Cookieless, no banner needed.', owner: 'brian', state: 'open' },
  { id: 73, title: 'Move vendor payments to Mercury', why: 'One named virtual card per vendor. Get Vercel, Supabase, Twilio, Hologram, Workspace, Namecheap, Resend, KORE and Anthropic off personal cards so the LLC’s books are clean from month zero. Vercel and Supabase receipts still land in the personal inbox.', owner: 'brian', state: 'open' },
  { id: 19, title: 'Supabase auth config', why: 'Enable the Google provider and fix the Site URL — it still points at vercel.app, so auth emails and redirects land wrong.', owner: 'brian', state: 'open' },
  { id: 3, title: 'Set the Greenville parcel service URL', why: 'Paste the Greenville County parcel MapServer layer URL (gcgis.org ArcGIS REST directory) into NEXT_PUBLIC_PARCEL_SERVICE_URL in Vercel. Turns on parcel lines and tap-for-owner on the map.', owner: 'brian', state: 'open' },
  { id: 74, title: 'TAT141 solar accessory', why: 'Ask Teltonika Americas (Billy) whether a solar charging accessory exists — at 5-minute tracking the battery alone will not last on machines parked outside; otherwise wire to 12/24 V aux.', owner: 'brian', state: 'open' },
  { id: 75, title: 'Confirm: QSBS / C-corp and equity-gifting conversation', why: 'Carried only on the retired Aug 22 to-do page: CPA on QSBS/C-corp conversion, attorney on equity gifting — the five-year clock only starts when shares exist. Say whether this is still wanted.', owner: 'brian', state: 'open' },

  // ── Build, open ──────────────────────────────────────────────────────
  { id: 100, title: 'OpenFreeMap vector basemaps — crisp at any zoom, no key, no vendor stamp', why: 'The keyless Esri fallback blurs past zoom 16 and CARTO wants a key. OpenFreeMap serves free vector tiles with dark/positron/liberty styles (we already pull its buildings). Rendering the dark base as vector layers under ours ends the raster-provider dependency for good; the B/W and Aubergine tints move to paint on those layers.', owner: 'build', state: 'open', sev: 'warn' },
  { id: 94, title: 'Provisioned-IMEI allow-list — stop IMEI squatting', why: 'sec-check P1: any self-serve signup can quick-add an unclaimed 15-digit IMEI and receive the rightful owner’s telemetry (082 stops the second claim, not the wrong first one). We ship every device, so a provisioned_trackers(imei, company) table filled at shipment, checked by scan/quick-add/bulk import and the flespi ingest, closes it.', owner: 'build', state: 'open', sev: 'warn' },
  { id: 95, title: 'Register devices in flespi + device-topic webhook (clone detection)', why: 'sec-check P1: Teltonika identifies a device by IMEI alone, so a clone with a known IMEI can write positions for the real truck. Registering each ident in flespi and subscribing to the device topic means only known devices reach us and flespi flags the connection conflict. The ingest now drops future/ancient timestamps (1 Sep) as the first layer.', owner: 'build', state: 'open', sev: 'warn' },
  { id: 103, title: 'Migration runner: no-transaction marker + lock_timeout for hot-table DDL', why: 'sec-check on 087: the runner wraps each file in one transaction, so CREATE INDEX on asset_locations held a SHARE lock (ingest inserts wait) and the DROP INDEX queued an ACCESS EXCLUSIVE lock behind every map read for the whole file. A leading `-- migrate: no-transaction` marker would allow CREATE INDEX CONCURRENTLY; DROP INDEX on hot tables gets its own file with SET LOCAL lock_timeout and a caught lock_not_available.', owner: 'build', state: 'open' },
  { id: 104, title: 'Debounce zone create/reshape replays', why: 'Every zone save with a changed boundary replays 365 days of the company’s pings through rebuild_zone_usage (service role). Bounded per call since 087, but a member dragging a corner ten times is ten full-history rescans. Skip when the same zone was rebuilt in the last 60 s.', owner: 'build', state: 'open' },
  { id: 96, title: 'Shared timing-safe verifyCronBearer()', why: 'Fifteen cron/diag routes compare the bearer with plain ===. Not exploitable in practice, but one shared helper with the house HMAC + timingSafeEqual pattern is the right shape.', owner: 'build', state: 'open' },
  { id: 97, title: 'Sweep P2 polish batch (1 Sep production QA)', why: '/command HIDE label vs MAP TOOLS tab · /welcome phone card squeeze · /activity dead-end for Admins (hide the link) · report mini-chart axis text · /qr URL wrap · FEMA flood server probe ERR · /finance revenue-per-employee off the placeholder headcount · /assets/onboard “no hardware” copy vs 20 assets · store screenshot “Geofenced” caption re-shoot.', owner: 'build', state: 'open' },
  { id: 98, title: 'Move PostGIS to the extensions schema', why: 'spatial_ref_sys is owned by the extension, so 086 could not enable RLS on it and the Supabase linter will keep one critical row. ALTER EXTENSION postgis SET SCHEMA extensions (check PostgREST search_path first) clears it for good.', owner: 'build', state: 'open' },
  { id: 88, title: 'Absolute last-seen date + time on the assets list', why: 'Brian, Aug 28: tools (and really every asset) should show what day and time they were last seen — not just “3d ago”.', owner: 'build', state: 'open' },
  { id: 89, title: 'Ping-dots layer on the timeline', why: 'An option to draw every true GPS fix as a dot, so a trail can be read against the raw pings. Honest about rollups past 30 days.', owner: 'build', state: 'open' },
  { id: 90, title: 'Shared requireEdit() gate on every asset write action', why: 'Tracker + delete actions now gate on canEdit (lib/actions/trackers.ts, 4 Sep); the remaining asset write actions (create/update/photos/import) still run on role-free service clients — one shared gate for all of them. sec-check 4 Sep: assets + device_onboarding RLS policies are FOR ALL, so a viewer can still set deleted_at / tracker_id or plant registry rows straight through PostgREST — the DB layer needs write policies keyed on role, not just the action layer.', owner: 'build', state: 'open' },
  { id: 76, title: 'Convoys into the AI context', why: 'Convoys are on the map but not in what the assistant reads — “who was riding with the RAM at 2 PM” should answer from the same motion-agreement math.', owner: 'build', state: 'open' },
  { id: 80, title: 'Fault codes → work orders', why: 'A stored fault code on a machine should open or annotate a work order the way overdue schedules already do.', owner: 'build', state: 'open' },
  { id: 38, title: 'Scope flespi ingest ident lookup per company', why: 'Mitigated 28 Aug: ingest lookups filter active=true and 082/084 guarantee one active owner per 15-digit IMEI; bulk import refuses cross-tenant collisions. Still open for non-IMEI tracker ids — needs a production duplicate check, then the schema fix on the other write paths.', owner: 'build', state: 'open' },
  { id: 35, title: 'Reconcile setup.sql with the migration series', why: 'setup.sql is still migrations 001–010 concatenated (its own header says so); the series is at 086. Regenerate it from the full series, or point GO-LIVE at scripts/migrate.mjs and retire it.', owner: 'build', state: 'open' },
  { id: 79, title: 'Open-data layers ranked 30 Aug', why: 'FAA TFR + LAANC ceilings (serves the daily Mavic flights), POI tap-for-phone/hours via Nominatim/Overpass, NWS alerts + USGS river gauges for pour/flood. Verified by live probes; boats, freight rail and arrivals boards are honest NOs.', owner: 'build', state: 'open' },
  { id: 78, title: 'iOS push (APNs) after Apple clears', why: 'Capacitor registers APNs tokens; our sender speaks FCM. Either an APNs key in Firebase + the FCM iOS SDK, or teach lib/push.ts APNs HTTP/2 for platform=ios. Post-TestFlight.', owner: 'build', state: 'open' },
  { id: 91, title: 'Memo cron scale past ~25 companies', why: 'The monthly owner memo composes serially; batch or parallelise before the Founding 25 fill up.', owner: 'build', state: 'open' },
  { id: 44, title: 'Tool trailer gateway', why: 'Wired FMM650 inside the trailer plus manifest alerts — “you left the yard with 38 of 40 tags.”', owner: 'build', state: 'open' },
  { id: 42, title: 'Vehicle & equipment camera pilot', why: 'DualCam-class over the Teltonika rails. Research says this likely needs FMC650 (Cat 1), not the FMM650 we own.', owner: 'build', state: 'open' },
  { id: 8, title: 'Zone financials', why: 'Contract bid, change orders and cost-code budgets against the DCG master list.', owner: 'build', state: 'open' },
  { id: 15, title: 'Map wow-pack tier 2', why: 'Bid Ghost, storm-$ ledger, vendor money map, then/now split.', owner: 'build', state: 'open' },
  { id: 16, title: 'Wow-pack P2 follow-ups', why: 'Deferred from the 12 Aug ship-check.', owner: 'build', state: 'open' },
  { id: 21, title: 'UX sweep batch 2', why: 'Deferred audit items.', owner: 'build', state: 'open' },
  { id: 12, title: 'UI polish tier 2', why: 'Motion pass, empty states, haptics.', owner: 'build', state: 'open' },
  { id: 34, title: 'Nationwide parcels add-on', why: 'Evaluate Regrid vs ReportAll and price it as an upsell.', owner: 'build', state: 'open' },

  // ── Shipped ──────────────────────────────────────────────────────────
  { id: 147, title: 'Azuga: the battle brief', why: 'Brian, Sep 21, with a screenshot of Azuga’s Facebook ad (real-time GPS, auto maintenance alerts, driver behaviour scores, geofence theft alerts, a dashcam): “Make sure we can destroy these guys and swallow them whole.” docs/COMPETITORS.md now carries Azuga with sourced pricing ($25–35 per vehicle a month, a $49.99 dashcam add-on, a 36-month contract when the camera is in), our answer to each of the four ad claims (all four are live here), the honest gaps (video, fuel-card import, driver rewards, ELD) and the ranked build list to close the ones worth closing.', owner: 'build', state: 'done' },
  { id: 146, title: 'Truck readings: every OBD data point, in words a contractor uses', why: 'Brian, Sep 21: “make sure every data point that is being sent is captured … dials on the asset pop-up and on the main asset page … RPMs, battery level etc. Similar to what they would see on a truck … a full master list of what the Teltonika OBD device CAN do, then what is being received for a particular truck.” Every fix already kept the tracker’s whole parameter bag; what was missing was the reading of it. The map panel and the asset page now show dials for RPM, speed, coolant, fuel, the 12-volt battery and engine load, a plain-words health line (“Check engine: 5 codes · driven 23,552 mi with the light on”, “Battery getting weak”, “No truck power”), then every other reading the unit has ever sent — converted to °F, mph, miles, gallons — and, honestly, the list of what this truck’s computer does not answer for. The master list is code (lib/telemetry-catalog.ts, every Teltonika element with its plain-English meaning); each truck’s own set is one stored row kept current at ingest (migration 115); the asset page adds a seven-day low/high/avg trend per reading. Ask AI and the MCP door read the same facts. Found on the way: the F350 has been driving with five trouble codes and 23,500 miles on the check-engine light; the RAM 2500’s computer answers only fuel and VIN; the F650, F750 and Truck 3 answer nothing over the port (medium-duty trucks speak J1939 — the wired CAN unit is the fix); and the panel had been showing the tracker odometer as 0 mi by treating kilometres as metres. Same night, from the reviewer pass (migration 117): the readings fold refuses hostile keys and non-time timestamps (one bad direct-OBD body could have poisoned a truck’s row or the serving instance), a tracker swap now clears the machine’s stored map so it never keeps describing the unit it no longer wears, and the map panel no longer shows the previous truck’s check-engine line while the next one’s readings load.', owner: 'build', state: 'done' },
  { id: 145, title: 'The map’s search bar really asks the flight log now — on the live site, not just in demo', why: 'Brian, Sep 21, with a screenshot of N575LD in the map’s search box: “Where to search specific planes to get their flight list” — the box had answered with four addresses (N5 2LD, London…) and no aircraft. The tail-number search shipped Sep 12 and passed its browser check, but the check ran the demo render: the production map boots “shell first” and that branch handed the flight-log flag in as a hard false, so on hammertrack.ai the search box never asked the flight log and the aircraft popup never showed its “flight log & charts” link either. Reproduced on the live site at phone size (one geocoder call, zero flight-log calls), then fixed by passing the real permission — the same one that puts the Flight log tile in More. Also: when the flight log is asked and does not answer (rate limit, registry outage) the box now shows a row that opens the log for that tail instead of quietly showing addresses only. Reviewer pass the same hour: the airfield half of that row had never worked either (a field code opened the flight log on “No aircraft found” instead of the board — one shared reading of the search answer now serves the page’s three doors), Enter takes the fallback row when it is the only row, and tapping outside the box closes it the way the X does so a late answer cannot linger.', owner: 'build', state: 'done' },
  { id: 144, title: 'Aircraft card: airport names on the route, and climbing / descending with an arrow', why: 'Brian, Sep 19, of the card on a Frankfurt-bound A330 over Charleston: “Add names of airports here and vertical speed with an up or down arrow.” The filed route read RSW → FRA, codes only; it now reads Fort Myers (RSW) → Frankfurt (FRA) — the town people recognise, taken from the route service’s own airport record and falling back to our bundled airport database. Under altitude and speed the card now says what the aircraft is doing vertically: ↑ climbing 1,200 ft/min in teal, ↓ descending 800 ft/min in amber, or → level when the rate is within the noise, the same colours the Climb trail uses. Both come from data the map already had.', owner: 'build', state: 'done' },
  { id: 143, title: 'A device nobody has heard from in a day is gray — everywhere', why: 'Brian, Sep 19, of the Charleston RAM sitting “No signal · 24h ago” under a bright blue dot: “This should show gray or something for devices that have not been seen in quite a while.” The map faded a dot toward gray between 12 and 48 hours of silence, so a day-old fix was still two-thirds its own color — while the health watchdog had been calling that same unit silent since hour six. Now the fade starts at six hours and a device silent for a day is gray, full stop; the cluster sheet says “dark”, the Today card lists it as silent, and the trackers list dims it, all from one definition. Every hardware unit checks in hourly even asleep, so a day of nothing is the hardware being dark — unplugged, dead battery, no coverage — never a parked machine. Second pass the same night: the first ship changed nothing on Brian’s screen, because his map runs with trails on and the puck he sees is the trail-head layer, which had never learned the aging at all — only the plain live dot had. The heads now speak the same language on the Live range (a replay head keeps its color: yesterday’s position has no age).', owner: 'build', state: 'done' },
  { id: 142, title: 'Phones can now hear the EYE Beacons — the New Holland tag was invisible to every phone', why: 'Brian, Sep 19, standing beside the New Holland excavator with his phone: “What’s going on with this BLE? Not working even with my phone right beside it.” The tag (…B553) is registered exactly as the trucks report it — a zero UUID with the tag’s MAC on the end — and the trucks DO hear it and its siblings (4,700 sightings in two weeks). A phone hears the same tag differently: Android hands the app the bare MAC, and the matcher compared the two forms as whole strings, so no phone in the company had ever matched an EYE Beacon — every phone-gateway sighting of one was thrown away. The matcher now treats the two forms as the same tag, both ways round, with a 33-assertion harness so it stays that way. What it does not fix: a phone that was refused Bluetooth (the Tag scanner switch says so) or the F650’s tag rides — those were always fine.', owner: 'build', state: 'done' },
  { id: 141, title: 'Radar slide-out stays with the rail — no more floating in the middle of the map', why: 'Brian, Sep 19: “Right side radar buttons and features need to be addressed” and “Radar movement thing is weird out in space when right tray is minimized.” The radar frame chip (time, pause, scrubber) used to be placed once, beside the radar button, and never again — so it printed straight across the MAP TOOLS tab whenever the button column put the radar button at that height, and once the tray was tucked away the chip, or its lone orange chevron, hung in the middle of the map where the button had been. Now it belongs to the rail: with the tray out it sits flush on the radar button and steps left of the MAP TOOLS tab if their rows would cross; with the tray tucked it docks to the right edge at that same height like an edge tab — still there to pause or scrub the loop — and sits just above MAP TOOLS if they would cross. Re-measured every time the tray moves.', owner: 'build', state: 'done' },
  { id: 138, title: 'Talking to the app — one honest voice door, and the native recognizer in v1.5.2', why: 'Brian, Sep 19: “Talk to ai verbally button not working either.” Inside the Android app the microphone button was a lie: the WebView exposes the browser speech API but has no recognition service behind it, so the button showed, blinked red for a frame on tap, and did nothing. Now one module decides the door — the browser’s own recognizer on a computer or in Chrome, Android’s recognizer through a native plugin in the app from v1.5.2, and on an app build from before that the mic stays and SAYS what is missing on tap instead of blinking. Ask AI and the map’s search box share it. The native piece rides v1.5.2 (versionCode 13), which sits behind the same Play declaration as 1.5.1 — see the item above.', owner: 'build', state: 'done' },
  { id: 137, title: 'Share this view — this screen, to a teammate, by link or straight to their phone', why: 'Brian, Sep 19: “Need share option to send link to show certain screen setup to team members either thru app or thru link.” The export button’s fourth answer. It takes everything that makes the map read the way it reads right now — layers, basemap, camera, the time range and playhead, the machine being followed or open, the division filter — and makes it a short link (hammertrack.ai/x/…) that a teammate opens and lands on the same screen after signing in; or picks teammates from the roster and sends it as a notification whose tap opens the view (the list says who has no phone in the app yet, so nobody is told “Sent” about a phone that is not there). Company-scoped: a link means nothing outside the company, and what the recipient sees of it is still decided by their own visibility rules. Reviewer pass the same night: the link is made as the sheet opens (share sheets need the tap itself), a shared camera survives the fleet loading in behind it, a followed machine waits for its track, everyone gets a Shared map views switch of their own (on by default), and every send is counted — 25 people per send, 100 per link, 100 sends a day — so nobody can flood the roster. Migrations 113 + 114.', owner: 'build', state: 'done' },
  { id: 136, title: 'GIF, PNG and PDF exports save inside the app — as links', why: 'Brian, Sep 19: “GIF won’t save to phone.” The app has no download door — a download click is a no-op inside it and there is no share sheet — so the GIF (and the PDF before it) were built and handed to nothing, and the result sheet even claimed “Saved to your downloads”. Every finished export is now parked in private storage the moment it is done and comes back as a link: Save opens the file in the phone’s browser, which downloads it like any file on the web; Send puts the link in a text; Copy link copies it. Public by link on purpose — a replay GIF is meant to reach a client or a claim — unguessable, dead after 30 days, file removed with it. On a computer Save stays the instant download it always was.', owner: 'build', state: 'done' },
  { id: 139, title: 'Top up Anthropic API credits — Ask AI is answering from the built-in engine', why: 'Sep 19, 3:24 PM: the AI service refused with “Your credit balance is too low to access the Anthropic API”. The app did what it is built to do — answered from its own data, flagged the answer as plain, and paged you once (at most every 30 minutes while people ask) — but every question is a plain answer until this clears. FIX (two minutes): console.anthropic.com → Plans & Billing → add credits and turn on auto-reload so it never runs dry again. No redeploy: the next question uses the model. The same key feeds the monthly owner memo, the /finance trade classifier and the AI voice in the morning briefing; all keep working in plainer words meanwhile.', owner: 'brian', state: 'open', sev: 'stop' },
  { id: 140, title: 'File the Play “Photo and Video Permissions” declaration — it now holds back TWO app features', why: 'v1.5.1 (job photos keep their own GPS) has sat in Google Play as a draft since Sep 12 waiting on this one-time form; v1.5.2 (talking to the app, Sep 19) stacks behind it. Play Console → App content → Photo and Video Permissions — the wording and the 30-second screen recording it asks for are in docs/APP-STORE-PLAYBOOK.md. Then run the play-promote workflow (or say so and it gets run): the draft flips to a rollout, no rebuild. Until then installed phones run 1.4.1: photo GPS falls back to asking which job, and the mic says it needs the update.', owner: 'brian', state: 'open', sev: 'warn' },
  { id: 135, title: 'Set CRON_SECRET in Vercel — nine crons have been refusing to run', why: 'Found Sep 19 while shipping the lost-truck-power work: the health cron wrote no memory row because the secret it now required was never there — and neither had any other cron that requires it. Vercel only sends the Authorization header once CRON_SECRET exists, so every job that fails closed on it has been answering 401 since the day it went fail-closed: the hours ledger has not written since Aug 24, map trail rollups stopped Sep 10, the evening digest and Monday agenda have never gone out since the Sep 11 rework, the receipt-chase ladder, flight-log banking and airport boards have never run, the showroom simulator is parked. The map still moves because ingest does not depend on it, which is why nobody noticed. FIX (Brian, two minutes): Vercel → hello-world → Settings → Environment Variables → add CRON_SECRET = any long random string, Production + Preview → Redeploy. Everything catches up by itself: the ledger heals 30 days back, trails backfill from their watermark, the digests start that evening. The health cron now stays open when the secret is unset and says so once a day, so this cannot go quiet again.', owner: 'brian', state: 'open', sev: 'stop' },
  { id: 134, title: 'Lost truck power — the alert that fires when the plug comes out, and a health feed that speaks once', why: 'Brian, Sep 18–19. Truck 4 sat on the map as “No signal · 26h” with “Battery 41%” and “52 mph” beside it and nothing that said why — and the founder feed had pushed the same “2 hardware trackers are silent … check Hologram balance” line three times in sixteen hours. The unit had already told us: at 5:31 PM Thursday its power pin fell from 13.4 V to 1.7 V at 16 mph — the OBD plug came out — and it ran 24 minutes on its own battery before going dark. The Charleston RAM had done the same three times that week. NOW: every OBD unit’s power pin is read at ingest, and truck power gone for a minute of device time is one alert, pushed the minute it becomes a fact, in words that say what to do (the plug is out or the port has no power). A one-minute flicker never pages; power coming back clears the alert by itself. The map panel and the truck’s page read “No truck power — running on its own battery”. The health feed remembers what it has already said (migration 112): a unit that goes dark is announced once, with its diagnosis — lost truck power at T, or already on battery at its last fix, or had power and stopped checking in (coverage or SIM), or a battery unit — and a unit that comes back is announced once. “Hologram” is gone from the wording; the fleet is on KORE. Harness: scripts/power-loss-test.mjs, 42 assertions.', owner: 'build', state: 'done' },
  { id: 133, title: 'Who can see this asset — a per-asset visibility ladder, enforced in the database', why: 'Brian, Sep 18, with his phone and two battery units riding in his own truck and the crew’s map showing all three at his location: “Turn this off immediately … I do not want to be tracked as admin … I want to see everything. No one else should see those devices right now. Don’t lose the data … Need to be able to easily toggle who has visibility to certain assets.” Every asset now carries a level — Everyone · Managers+ · Admins · Owner only — set in one tap from a card on the asset page, and the level holds EVERYWHERE at once: map, lists, command center, replays, alerts, reports, Ask AI. It holds everywhere because it is enforced in the database (row-level security) rather than in each screen: a hidden machine’s pings, trails, alerts, site hours, service history, photos and tag pairings are hidden with it, and a tool tag aboard a hidden truck is hidden too, since a tag’s location IS its truck’s. Nobody can set a level above their own rank — an Admin cannot promise “owner only” — and the database refuses the write, not just the button. Trackers keep recording whatever the level, so nothing is lost when it changes. An owner’s phone is created owner-only and an Admin’s admins-only; crew phones stay visible, because clock-in tracking is the point of them. Migration 111.', owner: 'build', state: 'done' },
  { id: 132, title: 'Aircraft on the ground, a flight path coloured by what it was doing, and a card that gets out of the way', why: 'Brian, Sep 13: “I need to be able to minimize this pop up so that I can zoom around and see the flight path also I want the option to see a color coded flight path based on ground speed vertical speed Etc”, and “I have not seen airplanes on the ground like you see on Flight Radar 24 at GMU”. THE CARD minimises to its title bar, because looking at the path is exactly what you want the card out of the way for, and the colour key moves to its own strip so it survives the minimise. THE PATH takes a ramp — ground speed, vertical speed or altitude — stretched over the 5th–95th percentile of the flight itself, so one bad fix cannot squash it, and a fix that carried no such measurement paints GREY rather than a value nobody took. Vertical speed is DIVERGING about level, the same validated pair as the charts, because climb and descent are opposite states and not more-and-less of one thing. THE GROUND: aircraft the feed flags as on the ground used to be dropped outright — they come through now as their own layer, drawn from airport zoom in, flat and shadowless so a ramp reads as a ramp. What it cannot do, and the layer now says so: we draw what is TRANSMITTING, and a tied-down aircraft with its avionics off sends nothing, which is why a small field is genuinely empty overnight where FR24 shows a stale ghost. The switch then took three tries to actually work — the poll and the layer were both gated on the SKY layer, then the panel drew its rows from the registry while reading their on-state from a hand-kept list that omitted this one, then the smoothing loop had the same gate. A reviewer pass closed the rest: a selected aircraft’s trail outlived the live map and painted today’s flight across yesterday, and null measurements on the wire were landing in a Float64Array as zero — a whole flight drawn “dead level” under a legend that looked measured.', owner: 'build', state: 'done' },
  { id: 131, title: 'Fly a flight back, and one search box that takes a tail, a field or a route', why: 'The last two off Brian’s FlightRadar24 list. PLAYBACK: play/pause, scrub and 10×–120× on any flight — the plan view brightens the flown part and carries the aircraft while the three charts’ crosshair follows the same moment. Speeds are multiples of REAL TIME, not one fix per frame, or a sparse stretch of track would replay faster than a dense one; nothing animates while paused, and the pointer always wins over the replay. SEARCH: the one box now answers three ways — N628TS is an aircraft, KGMU or GMU is that field’s board, GMU-CLT or “GMU to CLT” is the board filtered to that route. Aircraft is tried FIRST on purpose, because a registration can look exactly like an airport code (N92 is both a tail number and a New Jersey field) and someone typing into a flight log means the aeroplane. A field nobody is watching still opens, with a line saying so.', owner: 'build', state: 'done' },
  { id: 130, title: 'Airport boards — what flew in and out of a field', why: 'Brian sent FlightRadar24’s Greenville Downtown departures board, which FR24 locks past 12 hours behind a paid tier. Nobody publishes this and no free endpoint answers “what used KGMU today” at any price, so it is assembled from what the flight log already does: a 20-minute sweep makes ONE call per watched field to see who is near it, reads the trace of any airframe not already banked today, and files the flights whose CONFIRMED origin or destination is that field. The board is then a plain query on two new columns — instant, no upstream calls, and a local circuit correctly shows as both a departure and an arrival. Rows carry tail, type, the other end, duration, distance and the touch-and-go count, and tapping one opens that aircraft’s own log. The honesty problem is bigger here than anywhere else in the log, because an empty board means either “nothing flew” or “nobody was looking yet” — so the page always shows when the field was first watched and when it was last checked, and the empty state says which. Same bargain as saving a plane: it records from the moment you add it. Ten fields per company, 60 upstream reads per sweep. Migration 110.', owner: 'build', state: 'done' },
  { id: 129, title: 'Touch-and-goes counted, and traffic-pattern consistency you can see', why: 'Brian, Sep 12, about his own flight: “need a way to show how many touch and gos were done etc. Vs categorizing as multiple flights. For example yesterday I went gmu to grd and did a bunch of touch and gos then back to gmu. Would be a nice feature to show traffic pattern consistency.” The second half already held — a touch-and-go never makes the four-minute ground stop that ends a flight, so the trip was already ONE flight. What was missing was saying what happened in the middle of it. A touch-and-go in ADS-B is a hole: the aircraft comes down the pattern, VANISHES for two or three minutes because small fields have no receiver coverage at runway height, and reappears climbing. So detection follows the dip, not the wheels — below 500 ft above the field, with hysteresis so a wobble on final is not two arrivals. Two false positives had to be designed out, both real: a flight starts low over the field it departed (that is a take-off, not an arrival, and it was inventing a phantom touch-and-go on every A-to-B trip), and a 152 nm round trip is not a “circuit” with a 42 nm downwind. On his actual flight it reads: 4 touch-and-goes at Greenwood County, pattern altitude held within 12 ft of 902 ft AGL, laps 4:58 ± 22s, downwind 2.0 ± 0.1 nm. Consistency is shown as a SHAPE — the laps drawn on top of each other at one scale, because three circuits that stack into a single line say more than any statistic. The count also rides the flight row, so a logbook scan shows it without opening anything. Migration 109; the harness now drives his real trace, 71 assertions.', owner: 'build', state: 'done' },
  { id: 128, title: 'Flight log — search a tail number, read every flight, chart what it was doing', why: 'Brian, Sep 12: “I want plane flight log history added. Should be able to search tail numbers, see all prior flights, save planes etc. Also altitude and ground speed and vertical speed charts.” Type any tail number (or a hex — you should not have to know which you are holding) and get every flight it has flown, each one opening into a plan view of the route plus three charts: altitude, ground speed and vertical speed, on one shared crosshair. The catch the whole design turns on: the free ADS-B archive keeps a ROLLING ~30 DAYS — probed, not assumed. So search answers instantly for the last month with nothing set up, and SAVING a plane is what starts writing its history down: a nightly cron banks that airframe’s finished flights into our own tables, where they outlive the upstream window. The save button is the feature, not a bookmark, and the page says so. Honesty rules that cost real work: on-the-ground is the feed’s own flag and never an altitude threshold (a jet parked at Denver reads 5,300 ft, and a threshold loses every high-field takeoff); a red-eye across UTC midnight is stitched back into one flight, but only when the halves meet in both time and space; and a stretch of cruise nobody saw take off or land is labelled a coverage fragment instead of being sold as an 11-minute flight at 25,000 ft. scripts/flightlog-test/run.sh drives two REAL archive files with 48 assertions and stands with the ledger and nav harnesses — run it after any change to the math. docs/FLIGHT-LOG.md.', owner: 'build', state: 'done' },
  { id: 127, title: 'Push notifications are per person now, and an admin can set them for anyone below them', why: 'Brian, Sep 12, on the notification rework: "No the push need to be per person and admins can go in to change this for people." Yesterday\u2019s fix got each summary to the right COMPANY; this gets it to the right PHONES. Five switches per person \u2014 theft alerts, their own missing receipts, the evening digest, the Monday agenda, the clock-out nag \u2014 stored on their profile (migration 107). A new crew member is quiet without anyone configuring them: everyone gets theft alerts and the receipt for a card they ran, but the company-wide summaries only default on for the people who run the company. Everyone can quiet their own phone from Settings \u2192 My phone, including an Associate whose role has no other settings; an admin sets it for anyone below them from the Team page — and the person sees who changed it and can change it back. Both switches have to say yes, so turning a summary off for the company still silences everybody. Review pass the same day: My phone got its own ungated route (/settings/phone), because Settings is an Admin-only view level and three of the four roles were 404ing on the one page nobody should need permission for; what we store is now SPARSE, so an untouched switch keeps following the role (promote a Foreman and the nag turns itself on); a removed employee’s phones are deleted with their profile and dropped by the resolver, so a leaver stops getting the company’s theft alerts; and the missing-receipt TEXTS answer to the same switch as the pushes — turning it off used to still buy six texts over two weeks.', owner: 'build', state: 'done' },
  { id: 128, title: 'The export button works now — and gives you PDF, PNG or GIF', why: 'Brian, Sep 12: “PDF button seems to not be working. When you click button i should see 3 options to the left — PDF, PNG, and GIF.” It was not broken, which is almost worse: it built the PDF every time and then handed it to the phone in a way the app has no way to receive, so the button did nothing and said nothing. Now one tap opens three choices beside the button, and every one of them ENDS somewhere you can see — the picture on screen, or a plain sentence saying what happened. PNG is the one that always works inside the app: press and hold the picture and Android gives you Save and Send, no update needed.', owner: 'build', state: 'done' },
  { id: 127, title: 'Record the map as a GIF you can text', why: 'Brian, Sep 12, pointing at the Create PDF button: “what is the purpose of this? … need a gif creator within this as an option also.” The PDF hands someone a dated still of where everything was. This hands them the day — the truck leaving the yard, working the site, coming back — as a file that plays by itself in a text message, with nothing to open and nobody to log in. New button on the map rail, right under Create PDF: pick how long it plays, how smooth, and how big (it tells you the file size before you wait, and warns when it is bigger than a carrier will text), hit Record, then Save it or Send it straight from your phone. Only the map is in the picture — no buttons, no timeline. Works on any range you can replay.', owner: 'build', state: 'done' },
  { id: 126, title: 'Turn-by-turn navigation inside the app — voice, re-routing, heading-up map', why: 'Brian, Sep 12: “I want turn by turn navigation.” Directions used to be a list you read before you left, with a hand-off to Google for the actual driving. Now Start turns the map into a navigator: the turn you are driving toward in big type with the distance counting down, the one after it on a second line, and a voice that calls it at a mile, a half mile, a thousand feet and again at the corner — mute is one tap and it remembers. Miss a turn and it re-routes on its own (three bad fixes, so one bad GPS reading in a parking garage does not send you around the block). The map turns with the truck, your dot rides ON the road instead of in the median, and panning to look ahead stops the chase until you tap Re-center. Arrival clock and miles left sit along the bottom, still honest that the time does not know about traffic. Google Maps stays one tap away in the panel. The guidance math has its own test harness that drives a real Greenville route foot by foot — it already caught a bug that would have called every turn a mile early and never said “turn now.”', owner: 'build', state: 'done' },
  { id: 125, title: 'Every phone is a tool-tag gateway, always, without anyone finding a switch', why: 'Brian, Sep 12: “same with phones being a ble gateway? This should happen always thru the app.” It shipped Sep 9 as a switch on the Tag scanner page, default off — which for a crew means never on. Now it is on from a phone’s first launch of the app and runs on every screen; the switch is how you turn it OFF on one phone. Always-on forced two battery rules: the radio listens ten seconds of every twenty instead of continuously, and the phone only checks where it is when it actually heard a tag, so a phone with nothing near it costs almost nothing. The first scan makes the phone ask for Bluetooth, so a one-time card explains why first — a prompt with no explanation earns a No that kills the feature on that phone for good. Web-only: it reaches installed phones on the next deploy, no store release and no new Play form. The review pass the same night caught five real ones and all are fixed: restarting the listen each window would have re-thrown Android’s Bluetooth permission dialog over the person every twenty seconds — and a second “Don’t allow” is permanent, exactly what the card exists to prevent; the card itself was being drawn UNDER the location sheet on a new phone and counted as shown; the listen kept running in a pocket after the app left the screen; a truck parked with five tagged tools would have written about 1,800 near-identical location rows a day into the table the hours ledger reads; and a person who turned Share location OFF had their dot quietly put back on the map by the gateway — it now stands down instead. A phone with Bluetooth switched off also says so now, instead of claiming to be listening.', owner: 'build', state: 'done' },
  { id: 123, title: 'Notifications: one door per company, quieter defaults, and an off switch in every email and text', why: 'Brian, Sep 11: two evening digests landed on his phone in the same minute and one was another company\u2019s day \u2014 "fix whatever is causing this … cut down on clients feeling too spammed … add a link in texts and emails to go straight to turn off or change notifications." The evening digest, Monday agenda and still-on-the-clock crons each looped EVERY company and pushed to one global founder webhook: a notification per company per night, every customer\u2019s fleet and crew names on a topic they don\u2019t own, and nothing the customer could switch off. All three now deliver to the company\u2019s own phone/email/text on its own schedule, the founder mirror is owner-only and fails closed, the evening digest defaults to a phone notification only, and the Monday agenda and clock-out nag both default OFF. Separately: saving any setting used to silently switch the 6 AM briefing back on. Every summary email and text now ends with a 65-character link to a no-login page with a switch per summary and Turn everything off. The review pass caught four more: a run killed between the send and the stamp re-sent the same digest an hour later (the slot is claimed first now), trial accounts with no assets could starve every real customer out of the batch, job-cost dollars were about to go to every crew phone including roles that are denied costs, and the theft-alert path still texted a customer’s alerts to the founder’s fallback number when they had not set their own. Migration 106, docs/NOTIFICATIONS.md.', owner: 'build', state: 'done' },
  { id: 121, title: '/map crash on older Android phones fixed for good: the map’s background workers get the same fix the page got', why: 'Brian’s phone paged “Object.hasOwn is not a function @ /map” three more times on the night of Sep 8 — after the Sep 4 fix. That fix covered the page; the map engine also parses tiles in background workers, which have their own world and still hit the missing function on Chromium-92-era Android WebViews and Samsung Internet. Every worker now loads the same one-line shim before it touches a tile.', owner: 'build', state: 'done' },
  { id: 120, title: 'Stacks: a cluster on the map says what is in it, a tap lists it, zone names show how many are there, the Command Center shows each site by kind', why: 'Brian, Sep 9: “revisit the multiple items in one general area and ability to cleanly show this on the map (and on command center). I really liked the number beside a truck showing how many ble devices it was hauling.” A blob used to be just a number. Now it reads “2 trucks · 1 machine · 5 tools aboard”, tapping it lists every truck, machine and person in it with its state and its hauling count (one more tap opens the asset; Zoom in is still there), every job-site name carries “4 here” while anything is inside, and the Command Center’s Site presence rows break each site down by kind. The same stacks reach the AI layer through list_assets.', owner: 'build', state: 'done' },
  { id: 118, title: 'Time clock v2: location required to clock in, the phone records the whole shift (in the background on the new app build), GPS-verified time cards with payroll export and QuickBooks push', why: 'Brian, Sep 9: “clock in also a must and mandatory tracking thru app while clocked in … native background tracking is a must.” Clock-in now needs a location fix. While a shift is open the phone keeps reporting where it is — with the screen off once the v1.4.0 app is installed — and /timecards turns that into the week: paid hours split regular and overtime at 40, hours by job site, where each clock-in and clock-out happened, and how much of the clocked time the phone actually placed on the site (the “GPS-verified” number). Flags say what to look at: still clocked in, no GPS, mostly off-site, long shift, edited. Export the week as CSV for payroll or push a day to QuickBooks; managers correct an entry and the recorded times stay on the record. The same facts feed Ask AI and the Agent Interface (time_cards).', owner: 'build', state: 'done' },
  { id: 64, title: 'Android v1.2 submitted to Play (2 Sep) · releases now hands-off (versionCode 6 uploaded by the workflow, 3 Sep)', owner: 'brian', state: 'done' },
  { id: 117, title: 'Receipts land in QuickBooks the right way: the photo attached to the Purchase, the line billed to the job, the card swipe named', why: 'Brian, Sep 9: “qbo receipt attachment is part of the story on receipts.” Approving a receipt used to post a Purchase with the photo URL pasted into the memo and no job on it. Now the photo rides as a real attachment (the paperclip on the transaction), the line is billed to the job site’s QuickBooks customer, the expense account follows the category, a card-swipe receipt pays from the Credit Card account, and the memo names the card, the person, the merchant and the date. Wakes up the day QuickBooks is connected in production (docs/QBO-GO-LIVE.md).', owner: 'build', state: 'done' },
  { id: 116, title: 'Trackers first, then a machine: Add trackers (scan) → Put on a machine, one help guide per device type', why: 'Brian, Sep 9, setting up a non-technical owner in Charleston: “streamlined, easy, and obvious … added as trackers then seamlessly added to an asset. need a thorough how-to document for each device type.” Trackers → Add trackers scans the label barcode (IMEI or the MAC on a tool tag) and files the box in the drawer with its model known from the number; each drawer row has Put on a machine (pick an existing one or name a new one there) and a fold-out install card for its model. Tool tags now sit in the drawer too and say which truck last heard them. Help: Truck unit · Battery GPS unit · Tool tags; docs/CUSTOMER-SETUP.md is the printable how-to. Review pass the same night: the Play app never declared the camera permission, so in-app scanning silently fell back to typing — v1.3.1 fixes it (installed phones scan after the update); a tracker another company owns can no longer be claimed from its drawer; a failed put-on no longer leaves an empty machine behind.', owner: 'build', state: 'done' },
  { id: 115, title: 'Phones hear tags: a switch on the Tag scanner page makes the phone a BLE gateway while the app is open', why: 'Brian, Sep 9: “phone as ble gateway is a must.” Until now only a truck’s Teltonika box could hear a tool tag. The phone scans continuously while the app is open, keeps the loudest reading per tag over each 20 seconds and reports what it heard with where you were — through the exact same matcher, strongest-signal rule and custody history the trucks use, so a tool near you shows on the map as riding with you. The one matcher now lives in lib/ble-sightings.ts and understands hex, decimal and shorthand tag ids the same way. Scanning with the app closed is the native background update (task #57).', owner: 'build', state: 'done' },
  { id: 114, title: 'Job photos on the map: a camera button, a Google-Photos-style layer (heat → counts → the pictures), a /photos page, and daily logs that require a photo', why: 'Brian, Sep 9: “daily reports which should require photos … a separate option within the app to take photos or add photos which are geotagged as a layer on the map — we really like how Google Photos map does this with heatmap when zoomed in to a site.” Every job photo now knows where it was taken and files under the site it fell in (migration 101). Zoomed out you see the heat of where the crew shoots; closer, orange counts; at a site, the pictures themselves — tap one to open it. The 📷 button on the map and the Photos page take more; gallery photos use the location inside the picture. Clock-out waits for at least one job photo.', owner: 'build', state: 'done' },
  { id: 113, title: 'Receipt chase v2: push → text → owner, an in-app bar on every screen, receipts pinned on the map, a test-swipe button', why: 'Brian, Sep 9: “step 1 is the pushed notification to the correct person of whomever’s card was run and annoy the hell out of them until they take a picture of the receipt … these should also be a layer to be shown on the map.” The ladder now runs every 15 minutes (15 m · 1 h · 4 h · 24 h with the owner told · 7 AM and 5 PM after that), texts the cardholder’s cell, and every push opens the camera on tap. In the app an amber bar follows the cardholder onto every screen until the photo is in. Swipes are pinned on the map where the truck was (red), captured receipts where the photo was taken (teal). Receipts → Send me a test swipe proves the whole loop; the readiness chips say which leg still needs a key.', owner: 'build', state: 'done' },
  { id: 112, title: 'Radar: quality-controlled MRMS frames, no more bird disks, no more stitched frames', why: 'Brian, Sep 6: “what is going on with radar” — smooth green disks 60–80 miles across centered on every radar site (dark dot in the middle) and a hard rectangular seam east of Columbia. The disks were migrating birds and insects in clear-air mode on the raw NEXRAD composite; the seam was the loop re-pointing one tile source every 0.7 s and drawing whichever tiles had arrived. Now: IEM’s archived MRMS reflectivity (NOAA’s quality control strips non-weather echoes; 2-min frames since 2015, same tile cache), and the loop double-buffers — a frame shows only once every one of its tiles is in, the next frame waits its turn. Verified frame by frame on /map and /command, every timeline range.', owner: 'build', state: 'done' },
  { id: 111, title: 'Heat map reads like weather radar: green travel threads, dwell blobs green → yellow → orange → red → pink', why: 'Brian, Sep 5: “a very narrow radius… only green showing the travel, then green to yellow to orange to red where it sits, pink as the highest.” Kernels are tight so the COLOR carries the story; density = time on the spot × machines there.', owner: 'build', state: 'done' },
  { id: 110, title: 'Glance language: moving dots blink, stale dots fade to gray with an age badge, 3-finger area measure, brand + company marks tap somewhere', why: 'Brian, Sep 4: moving assets should be obviously blinking; know how stale the data is (a day or two → gray); three fingers for an area; the logo and company icon must do something. Live dots fade toward gray from 12h to 48h and carry “3h / 2d” badges; the pulse ring breathes while live or playing; the HammerTrack mark zooms to the fleet; the company mark opens Company settings · Team · Trackers · Sign out.', owner: 'build', state: 'done' },
  { id: 109, title: 'Command Center on phones: KPI strip, ticker up top, PANELS sheet with the wall’s instruments, no duplicate Ask AI', why: 'Brian, Sep 4: “ticker covering things up… Ask AI twice… bring desktop features to mobile or it’s not worth having.” The six wall numbers ride under the header, the ticker is a slim strip below them, and a PANELS edge tab opens fleet activity, site presence, Worth a look, fleet status, the event log and the fleet board in a bottom sheet.', owner: 'build', state: 'done' },
  { id: 108, title: 'Timeline on phones: one screen, no side-scrolling; one Today (live edge) instead of Live + Today', why: 'Brian, Sep 4. Ranges are an 8-cell grid, views a 4-cell control with the toggle that belongs to the active view, tools a labeled row. The Live pill is gone: Today opens at the live edge (blinking badge, playhead on now); drag back to replay, land on now to be live again. Live-only layers still key off the hidden live state.', owner: 'build', state: 'done' },
  { id: 107, title: '☀ Daylight on the timeline: the sun’s light follows the replay clock (Today · Yesterday · 7d · 30d)', why: 'Brian, Sep 4: “show the Sun’s light moving across wherever we are viewing.” The real day/night layer now rides the scrub with a smooth ten-band twilight (golden hour → civil → nautical → astronomical → night), a sun readout at map center, and it greys out on YTD/All where a sweep would strobe through hundreds of nights.', owner: 'build', state: 'done' },
  { id: 106, title: 'Assets list says where each machine is — its zone, else the nearest address, else city + state', why: 'Brian, Sep 4: “easily and quickly see where each asset is.” One pin line per row, searchable. Zones answered from our polygons; off-site spots reverse-geocoded once per ~100 m cell through free OSM/BigDataCloud lookups and remembered (migration 098), so the list stays instant and repeat visits cost nothing.', owner: 'build', state: 'done' },
  { id: 105, title: 'Tracker put-on brings its back-dated pings along (097); Trackers page scrolls on phones', why: 'Brian, Sep 4: the TAT141 taken off the placeholder "tat141 - 6" and put on the Silverado "as of 9/3 8 PM" left that whole day on the placeholder, which kept sitting on the map at the truck’s spot. An attach from the drawer now pulls the pings from the machine the box came off (from the time you pick up to the moment it was pulled), Undo returns them, and 097 repaired the Silverado’s day in place.', owner: 'build', state: 'done' },
  { id: 102, title: 'Disk IO diet — hourly ledger rebuild bounded to 3 days, trails rebuild only changed days, two indexes (087/088)', why: 'Also fixed the ledger bug the old rescan hid: usage_daily forgot every site visit that ended before the hourly window’s start on its first day; 088 re-banked 90 days once. Proven equal to a from-scratch build by scripts/ledger-test.', owner: 'build', state: 'done' },
  { id: 93, title: 'Founder audit pass — board refresh, marketing truth sweep, SEO basics, security headers', owner: 'build', state: 'done' },
  { id: 92, title: 'RLS lockdown — deploy ledger + PostGIS table (migration 086)', owner: 'build', state: 'done' },
  { id: 63, title: 'Android v1.2 (versionCode 5) + hands-off Play upload step', owner: 'build', state: 'done' },
  { id: 62, title: 'Launcher icons — navy ground, amber signal arcs', owner: 'build', state: 'done' },
  { id: 61, title: 'Sparse trails drawn honestly + route/plane rate limits', owner: 'build', state: 'done' },
  { id: 60, title: 'Navigation wave — Places, directions, convoys, smooth planes, location primer', owner: 'build', state: 'done' },
  { id: 59, title: 'Store listing pack refresh — real screenshots, tagline, feature graphic', owner: 'build', state: 'done' },
  { id: 58, title: 'App shell opens /map + sign-in polish', owner: 'build', state: 'done' },
  { id: 57, title: 'Map selection & state language — dim the rest, gray the dead, ring the tools', owner: 'build', state: 'done' },
  { id: 56, title: 'Bulk add, spreadsheet style (/assets/import)', owner: 'build', state: 'done' },
  { id: 101, title: 'Roles v2: Master Admin, view-levels table, View-as, Associate, AI firewall + ladder-only convo visibility (migration 094)', owner: 'build', state: 'done' },
  { id: 100, title: 'Trackers: Unassigned drawer, 5-case Tracker sheet, 30-day undo + Recently deleted (/trackers, migration 092)', owner: 'build', state: 'done' },
  { id: 55, title: 'Scan-to-map onboarding (/assets/scan)', owner: 'build', state: 'done' },
  { id: 54, title: 'Per-asset map icons', owner: 'build', state: 'done' },
  { id: 53, title: 'Monthly owner memo + Ask AI in the chrome', owner: 'build', state: 'done' },
  { id: 52, title: 'Insights engine — 8 detectors, anti-cry-wolf schema', owner: 'build', state: 'done' },
  { id: 51, title: 'Full-site audit + logged-in review fix batch', owner: 'build', state: 'done' },
  { id: 50, title: 'KORE SuperSIM no-cable onboarding playbook, proven on the first FMM00A', owner: 'build', state: 'done' },
  { id: 49, title: 'Showroom company + simulator cron', owner: 'build', state: 'done' },
  { id: 47, title: 'Device onboarding single pane (/assets/onboard)', owner: 'build', state: 'done' },
  { id: 48, title: 'Founder board at /board', owner: 'build', state: 'done' },
  { id: 4, title: 'Exact hours & cost engine (056 ledger)', owner: 'build', state: 'done' },
  { id: 18, title: 'Tow-latency wording — softened to “alert on your phone” pending Twilio', owner: 'build', state: 'done' },
  { id: 39, title: 'Trail rollups + map viz polish', owner: 'build', state: 'done' },
  { id: 37, title: 'Demo realism overhaul', owner: 'build', state: 'done' },
  { id: 36, title: 'Phone gesture wave', owner: 'build', state: 'done' },
  { id: 33, title: 'Map declutter round 2', owner: 'build', state: 'done' },
  { id: 32, title: 'Clock-out replay staleness policy', owner: 'build', state: 'done' },
  { id: 31, title: 'Hand-scrubbable radar timeline', owner: 'build', state: 'done' },
  { id: 30, title: 'Map / layers UX study + fix batch', owner: 'build', state: 'done' },
  { id: 29, title: 'Idempotency & visibility hardening', owner: 'build', state: 'done' },
  { id: 28, title: 'Unified Ask assistant — one brain, three doors', owner: 'build', state: 'done' },
  { id: 27, title: 'In-app help centre + support scaffolding', owner: 'build', state: 'done' },
  { id: 26, title: 'Agent Interface (MCP server)', owner: 'build', state: 'done' },
  { id: 25, title: 'Multi-tenant hardening for customer #2', owner: 'build', state: 'done' },
  { id: 24, title: 'Offline field queue', owner: 'build', state: 'done' },
  { id: 23, title: 'QBO timesheet push', owner: 'build', state: 'done' },
  { id: 22, title: 'Per-company ingest API keys', owner: 'build', state: 'done' },
  { id: 20, title: 'Site-wide UX sweep', owner: 'build', state: 'done' },
  { id: 14, title: 'Map wow-pack', owner: 'build', state: 'done' },
  { id: 13, title: '/command first-switch TypeError', owner: 'build', state: 'done' },
  { id: 11, title: 'Admin-configurable daily log', owner: 'build', state: 'done' },
  { id: 10, title: 'Store listing pack', owner: 'build', state: 'done' },
  { id: 9, title: 'BusyBar across every slow flow', owner: 'build', state: 'done' },
  { id: 7, title: 'Tool presence hours from the pairing log', owner: 'build', state: 'done' },
  { id: 6, title: 'Asset sheet close on phone', owner: 'build', state: 'done' },
  { id: 5, title: 'Zone hours/cost bar chart', owner: 'build', state: 'done' },
  { id: 2, title: 'Migration 055 + auto-migrations', owner: 'brian', state: 'done' },
]

export interface Stage {
  mark: string
  when: string
  title: string
  summary: string
  points: { text: string; tone?: 'ok' | 'wait' | 'no' }[]
  gate?: string
}

/** docs/PATH-TO-1B.md — valuation is arithmetic on ARR, so the stages are
 *  ARR milestones, not dates. */
export const STAGES: Stage[] = [
  {
    mark: '25', when: 'Stage 0 · now', title: "Founding 25 — prove it's a business",
    summary: '25 paying companies, under $100k ARR, near-zero churn. Funded by nothing but the monthly burn and your own time.',
    points: [
      { text: 'Pilot truck live since 6 Jul · Stripe billing live · Mercury live', tone: 'ok' },
      { text: 'Android app live in Play since 21 Aug; v1.2 built 1 Sep, upload pending', tone: 'ok' },
      { text: 'Apple org enrollment denied (4 Sep) — enrolling as Individual instead', tone: 'wait' },
      { text: 'PM Tier 1 money loop is the next real build', tone: 'wait' },
      { text: 'Zero paying customers today — this is the whole job', tone: 'no' },
    ],
    gate: '25 companies, and 3+ referrals that arrived unprompted.',
  },
  {
    mark: '$1M', when: 'Stage 1 · 2027–28', title: 'Prove distribution repeats',
    summary: '~350 companies at ~$250/mo blended. Valuation roughly $6–10M.',
    points: [
      { text: 'The theft-hook ad funnel, run properly across Upstate SC, then the Charlotte and Atlanta corridors' },
      { text: 'Equipment dealers as resellers — a tracker with every used-iron sale. One productive dealer is 5–15 customers a year, forever. Sign ten.' },
      { text: 'Expansion revenue starts: the $49 and $199 platform tiers lift ACV without new logos' },
    ],
    gate: 'CAC under 6 months of gross profit · net revenue retention above 100%.',
  },
  {
    mark: '$100M', when: 'Stage 2 · 2029–30', title: 'Prove the platform',
    summary: '~2,500 companies, ~$400/mo blended, $10–12M ARR at an 8–10× forward multiple.',
    points: [
      { text: 'Three engines running: SaaS (~60% of revenue), fintech attach, and the data layer' },
      { text: 'The financial layer is what makes a customer worth 3–5× their SaaS fee' },
    ],
  },
  {
    mark: '$1B', when: 'Stage 3', title: 'The arithmetic, not the fantasy',
    summary: '~$90–120M ARR. About 20,000 customers at ~$5k/yr blended — under 3% of just the US construction segment.',
    points: [
      { text: '~750,000 US construction firms with payroll; ~3.5M counting owner-operators; field services roughly double it' },
      { text: 'The risk was never market size — it is distribution and retention' },
    ],
  },
]

/** docs/PRICING-TIERS.md. Run's platform price stays unpublished publicly;
 *  this is the founder view, so it shows. */
export const TIER_ROWS: { label: string; track: string; operate: string; run: string; emphasis?: boolean }[] = [
  { label: 'Who it’s for', track: '"Where’s my stuff"', operate: '"Run my crews on it"', run: '"Run the company on it"' },
  { label: 'Tracked machine', track: '$8/mo', operate: '$8/mo', run: '$8/mo' },
  { label: 'Tool tags', track: '$3/mo', operate: '25 included', run: '100 included' },
  { label: 'Platform fee', track: '$0', operate: '$49/mo', run: '$199/mo', emphasis: true },
  { label: 'Map, theft alerts, geofences', track: '✓', operate: '✓', run: '✓' },
  { label: 'Time clock, logs, QR maintenance', track: '—', operate: '✓', run: '✓' },
  { label: 'QuickBooks sync', track: '—', operate: '✓', run: '✓' },
  { label: 'AI assistant + digest', track: '—', operate: '—', run: '✓' },
  { label: 'Users', track: 'Unlimited', operate: 'Unlimited', run: 'Unlimited' },
  { label: 'Typical customer · 8 machines, 12 tags', track: '$100/mo', operate: '$113/mo', run: '$263/mo', emphasis: true },
]

/** docs/COST-SCALE-2026-07.md */
export const COST_CURVE: { label: string; cells: string[]; emphasis?: boolean }[] = [
  { label: 'MRR', cells: ['$0', '$2,100', '~$11,000', '~$56,000'], emphasis: true },
  { label: 'SIMs in field', cells: ['~15', '200', '800', '4,000'] },
  { label: 'SIM + flespi COGS', cells: ['$5', '~$400', '~$1,360', '~$6,000'] },
  { label: 'Fixed infra', cells: ['$130', '$130', '~$300', '~$900'] },
  { label: 'Stripe fees', cells: ['$0', '~$70', '~$330', '~$1,650'] },
  { label: 'AI usage (Haiku dispatcher + monthly memo)', cells: ['$0', '~$30', '~$150', '~$700'] },
  { label: 'Total cost', cells: ['$135', '~$630', '~$2,140', '~$9,250'] },
  { label: 'Gross margin', cells: ['—', '70%', '81%', '83%'], emphasis: true },
]
export const COST_COLS = ['Now (pilot)', '25 customers', '100', '500']

/** docs/OPERATING-MODEL.md — the step-jumps in the cash curve. S1 is the one
 *  deliberate exception to the trigger rule: it fires at zero customers
 *  because the constraint it relieves is founder hours, not demand. */
export const HIRES: { role: string; trigger: string; cost: string; when: string; note?: string }[] = [
  { role: 'S1 — PT field sales & install', trigger: '0 customers — founder hours are the binding constraint, not demand', cost: '$800 base + $200/account', when: 'Sep 2026',
    note: 'DUE NOW — no hire recorded as of 1 Sep. Hired for the rolodex, comp weighted to commission. 60-day kill rule: under 8 demos/mo or 3 activated accounts → pure commission or part ways.' },
  { role: 'H1 — PT installer / support', trigger: '30 customers', cost: '—', when: 'absorbed by S1',
    note: 'Grow S1\u2019s hours at the 30-customer trigger instead of adding a second person.' },
  { role: 'H2 — FT ops / install tech', trigger: '90 customers', cost: '$5,400', when: 'Jul 2028' },
  { role: 'H3 — PT admin / CS', trigger: '110 customers', cost: '$1,200', when: 'Oct 2028' },
]

/**
 * The outreach plan — docs/BUSINESS-PLAN.md Phase 1 plus the Aug 28 S1
 * amendment. Ordered by expected yield, which is also the order to work it:
 * warm names first, because a beachhead is defined by who returns your calls.
 */
export const SELLING_MOTION: { step: string; detail: string }[] = [
  { step: 'The 25-name list', detail: 'Personal demo on YOUR live fleet, on your phone, at their yard. Close rate should be 40%+ with the Founding 25 offer.' },
  { step: 'Local dealer pilots (2)', detail: 'Free tracking on two Upstate dealers\u2019 rental fleets. Rental theft is THEIR pain — when it saves them once, they become the channel.' },
  { step: 'Contractor Facebook groups', detail: 'Where Upstate crews already talk. The theft hook travels by word of mouth in these faster than by ad spend.' },
  { step: 'The theft-hook ad funnel', detail: 'Facebook/Instagram → hammertrack.ai/demo → /register. Ad variants written and waiting in marketing/ad-variants.md.' },
]

export const S1_SHAPE: { label: string; value: string }[] = [
  { label: 'Who', value: 'ONE part-time field sales & install person, hired for their rolodex — dealer counter or sales guy, rental coordinator, retired super. Someone Upstate contractors already return calls from.' },
  { label: 'What they do', value: 'Demo on the showroom company, close with the DCG field-report one-pager, and do the first install on the spot — the offer\u2019s "first install done with you" becomes their job.' },
  { label: 'Comp', value: '$800/mo base (10–15 hrs/wk) + $200 per activated account + $1,000 bonus at 25. All-in ≈ $336/account at pace; payback stays ~6 months at founder-pricing margin.' },
  { label: 'Founder keeps', value: 'The first 3 demos (pitch calibration), the warm-intro list, and the account-level tasks — Twilio verdict, QBO keys, showroom seed.' },
  { label: 'Kill rule', value: '60 days. Fewer than 8 demos/month or 3 activated accounts → restructure to pure commission or part ways.' },
  { label: 'Cash', value: '~+$2.4k/quarter pre-close burn. Worst-case cumulative drawdown moves ~$8.5k → ~$11k. Still self-funding.' },
]

/** docs/COMPETITORS.md — the Aug 24 recon. Sell on friction, not features. */
export const COMPETITORS: { name: string; note?: string; price: string; friction: string; lead?: boolean }[] = [
  { name: 'Tenna', note: 'John Deere-owned since ~Feb 2026', price: '$15–30/asset, quote-only', lead: true,
    friction: '$5k–20k implementations. They do have BLE tags and claim QuickBooks now — sell on implementation cost, contract friction and small-crew fit, not missing features.' },
  { name: 'Samsara', price: '$27–60/vehicle', friction: 'Three-year contracts; small fleets prepay all three years up front.' },
  { name: 'Verizon Connect', price: '$23–45/vehicle', friction: '36-month auto-renew and a contract-trap reputation.' },
  { name: 'GPS Trackit', price: '$24–36/vehicle', friction: 'Month-to-month, but a leased-hardware exit trap.' },
  { name: 'FleetWatcher', note: 'AlignOps', price: '—', friction: 'Paving e-ticketing and hauler logistics. Heavy setup, different buyer.' },
]

export const VENDORS: { name: string; state: 'live' | 'warn' | 'stop' | 'idle'; stateLabel: string; note: string }[] = [
  { name: 'Mercury', state: 'live', stateLabel: 'live', note: 'Approved 5 Aug. One named virtual card per vendor. The opening deposit is owner capital, not income.' },
  { name: 'Stripe', state: 'live', stateLabel: 'live', note: 'Subscriptions live since 31 Jul — $8 machine / $3 tag prices, webhook wired. Founding-25 pricing applied per company.' },
  { name: 'Google Workspace', state: 'live', stateLabel: 'live', note: 'hammertrack.ai · sales@, hello@ and support@ all verified receiving.' },
  { name: 'Supabase', state: 'live', stateLabel: 'live · linter rerun due', note: 'Pro; billing entity is the LLC. The security advisor flagged two public tables without RLS on 31 Aug — fixed by migration 086 on 1 Sep. Rerun the linter to confirm it reads clean.' },
  { name: 'Vercel', state: 'warn', stateLabel: 'www broken', note: 'Apex healthy, auto-deploys master, migrations run on every build. www.hammertrack.ai serves the apex-only certificate → browser warning; add www as a redirect domain in the project. Web Analytics not yet enabled.' },
  { name: 'D-U-N-S', state: 'live', stateLabel: 'issued', note: 'Landed early Aug. Unblocks both app-store organisation accounts. Never file again — duplicates are slow to merge.' },
  { name: 'Twilio', state: 'warn', stateLabel: 'verdict unchecked', note: 'Toll-free verification has read “in review” since 30 Jul and no verdict email exists anywhere. Check the console. Voice still has no greeting — do not publish the number.' },
  { name: 'KORE', state: 'stop', stateLabel: 'invoice + call', note: '14 Aug invoice, card declined 18 Aug — status unknown. 13 SuperSIMs activating in KORE One; onboarding call unanswered since 26 Aug; connectivity agreement still pending in their system.' },
  { name: 'Google Play', state: 'live', stateLabel: 'app live · v1.2 in review', note: 'Organization account; com.hammertrack.app in Production since 21 Aug. v1.2 (versionCode 5) submitted 2 Sep. Releases are hands-off: the android-release workflow uploads itself (proven on the internal track 3 Sep). Confirm the developer-verification registration before 30 Sep. Listing still shows raw browser screenshots.' },
  { name: 'Google Ads', state: 'stop', stateLabel: 'paused', note: 'Account paused 31 Aug — advertiser verification incomplete by the deadline. Finish the verification tasks before any campaign can run.' },
  { name: 'Apple Developer', state: 'warn', stateLabel: 'org denied → individual', note: 'Organization enrollment DENIED as final (phone, 4 Sep, case 20000149520723). Going the Individual route: Apple Developer app → scan license + selfie → $99. Seller name becomes “Brian Dillard”; convert to Organization later. Denial email still to be read for the on-record reason (devprograms@apple.com is the appeal address).' },
  { name: 'Resend', state: 'warn', stateLabel: 'inbound off', note: 'Outbound email live (invites, digests, memo). Inbound is not enabled, so the receipt chase built 1 Aug has never fired.' },
]

export const ENV_PENDING: { text: string; tone: 'no' | 'wait' }[] = [
  { text: 'QBO_* — no customer can connect QuickBooks until this ships (docs/QBO-GO-LIVE.md)', tone: 'no' },
  { text: 'NEXT_PUBLIC_CARTO_KEY — optional: swaps the Esri fallback basemaps for CARTO’s retina tiles (board #99)', tone: 'wait' },
  { text: 'RESEND_INBOUND_SECRET — the receipt chase fails closed until it is set', tone: 'no' },
  { text: 'PLATFORM_OWNER_EMAILS — until it is set, the founder-page gate falls back to a weaker @hammertrack.ai domain check', tone: 'no' },
  { text: 'CRON_SECRET in Vercel — verify it is set: usage, trail-rollup, insights and memo crons all fail closed without it', tone: 'wait' },
  { text: 'GitHub Actions secret CRON_SECRET (diag probe) — PLAY_SERVICE_ACCOUNT_JSON is in', tone: 'wait' },
  { text: 'NEXT_PUBLIC_PARCEL_SERVICE_URL — turns on parcel lines and tap-for-owner', tone: 'wait' },
  { text: 'Supabase Auth Site URL still points at vercel.app, so auth emails land wrong', tone: 'wait' },
]

export const ENV_LIVE: string[] = [
  'Auto-migrations run on every master build — pushing a migration file IS the migration',
  'flespi channel 1401177 → webhook → ingest, verified end to end',
  'hammertrack.ai on Vercel since 5 Aug; the .com 301s to it; Workspace MX intact',
  'Stripe billing, Resend outbound and push registration all wired',
  'android-release builds a signed AAB from the 4 ANDROID_* secrets — proven on v1.2, 1 Sep',
]

export const RULES: { name: string; text: string }[] = [
  { name: 'Checks & balances', text: 'One reviewer pass (ship-check, truth-check, sec-check) per day that had major changes, scoped to that day’s diff — never a merge gate. Ship, review, fix what is real in a follow-up commit.' },
  { name: 'Release rule', text: 'Native-affecting merges bump versionCode/versionName and dispatch android-release without asking (Brian, 31 Aug). Play rejects a reused versionCode — jump higher when in doubt. iOS stays manual until Apple clears.' },
  { name: 'Sync rule', text: 'Any roadmap, to-do or cost change updates the system-map infographic, this board and the cost docs in the same commit. The graphic is a view of the roadmap; never let them drift.' },
  { name: 'Splash truth', text: 'Nothing on a marketing page may claim functionality that does not exist. Roadmap items say ROADMAP; shipped items may say LIVE. Every session that ships or re-scopes a feature re-audits the splash in the same commit.' },
  { name: 'Pricing sync', text: 'Any change to tiers, Founding-25 terms or the pilot offer updates /pricing, the splash ladder, /demo, the billing guide and the tiers doc — all in one commit.' },
  { name: 'Testing rule', text: 'Anything touching timeline, radar or history gets clicked through every range on both /map and /command. Nothing animates while the timeline is stopped.' },
  { name: 'Ship-to-live', text: 'Once validated, open the PR and squash-merge to master without asking. Live is where Brian reviews.' },
]

/** Standing marketing exposure — claims that are currently ahead of reality.
 *  Kept on the board so they can't quietly age. */
export const TRUTH_WATCH: string[] = [
  'QuickBooks is labelled “coming” on every public page as of 1 Sep — the integration is built; the Intuit app is not. Connecting (docs/QBO-GO-LIVE.md) flips the copy back.',
  'Theft-alert copy says “alert on your phone within minutes” (push), not “text” — the toll-free verdict is unconfirmed. Approved verdict → texts go back on.',
  'The receipt-chase “seconds after the swipe” line describes a built feature that is dark until Resend inbound is enabled.',
]

export const DOC_INDEX: { group: string; files: string[] }[] = [
  { group: 'Money', files: ['PRICING-TIERS.md', 'UNIT-ECONOMICS.md', 'COST-SCALE-2026-07.md', 'OPERATING-MODEL.md', 'BUSINESS-PLAN.md', 'QBO-GO-LIVE.md'] },
  { group: 'Strategy', files: ['PATH-TO-1B.md', 'GROWTH-PLATFORM.md', 'AI-RESILIENCE.md', 'COMPETITORS.md', 'FOUNDING-25.md'] },
  { group: 'Hardware & ops', files: ['DEVICE-ONBOARDING.md', 'TRACKERS.md', 'ROLES.md', 'TELTONIKA-DEVICES.md', 'FLEET-TELEMATICS.md', 'PROVISIONING.md', 'APP-STORE-PLAYBOOK.md', 'SHOWROOM.md'] },
]

/** Where each class of iron belongs — the allocation that stops someone
 *  carrying an OBD plug out to a Class-8 dash it cannot fit. */
export const IRON: { machines: string; fit: string }[] = [
  { machines: 'Peterbilt 567 · International LF627', fit: 'FMM650 + ALL-CAN300 — the dash is 9-pin Deutsch J1939, an OBD-II plug physically will not fit' },
  { machines: 'Sakai SW990 · LeeBoy 8500C · Sany PQ190', fit: 'FMM650 + CAN for true engine hours, fuel and fault codes' },
  { machines: 'Takeuchi TB235 and battery-only machines', fit: 'TAT141, wired to 12/24 V aux where the machine has it' },
  { machines: 'Light-duty trucks', fit: 'FMM00A in the OBD port — also the BLE gateway that tools ride on' },
]

export const BURN = [
  { amount: '$25', what: 'Supabase Pro' },
  { amount: '$20', what: 'Vercel Pro' },
  { amount: '~$48', what: 'Workspace, domains, mailbox' },
  { amount: '~$37', what: 'Twilio + QuickBooks' },
]

export function taskCounts(tasks: BoardTask[] = TASKS) {
  return {
    open: tasks.filter((t) => t.state !== 'done').length,
    brian: tasks.filter((t) => t.state === 'open' && t.owner === 'brian').length,
    build: tasks.filter((t) => t.state !== 'done' && t.owner === 'build').length,
    done: tasks.filter((t) => t.state === 'done').length,
    total: tasks.length,
  }
}
