'use client'

/**
 * Branded PDF engine — every "Create PDF" in the app goes through here so
 * each document opens the same way: the client's logo (Settings → Company),
 * company name, title, date line, and a footer with paging + the HammerTrack
 * mark. Letter-size, real margins, thought-out — not a browser print.
 *
 * jsPDF is dynamically imported so the ~300KB library never rides in the
 * main bundle; it loads the first time someone actually makes a PDF.
 */

export interface PdfBrand {
  companyName: string
  /** Client logo URL (companies.logo_url) — drawn top-left when present. */
  logoUrl?: string | null
  title: string
  subtitle?: string
}

export const PAGE = { w: 279.4, h: 215.9 } // Letter landscape, mm
export const MARGIN = 12

/** Load an image URL into a dataURL + natural size (for jsPDF addImage). */
async function loadImage(url: string): Promise<{ data: string; w: number; h: number } | null> {
  try {
    const img = new Image()
    img.crossOrigin = 'anonymous'
    await new Promise<void>((res, rej) => {
      img.onload = () => res()
      img.onerror = () => rej(new Error('logo load failed'))
      img.src = url
    })
    const c = document.createElement('canvas')
    c.width = img.naturalWidth
    c.height = img.naturalHeight
    const ctx = c.getContext('2d')
    if (!ctx) return null
    ctx.drawImage(img, 0, 0)
    return { data: c.toDataURL('image/png'), w: img.naturalWidth, h: img.naturalHeight }
  } catch {
    return null // logo unreachable — the header simply skips it
  }
}

export async function createBrandedPdf(brand: PdfBrand, orientation: 'landscape' | 'portrait' = 'landscape') {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'letter' })
  const pw = orientation === 'landscape' ? PAGE.w : PAGE.h
  const ph = orientation === 'landscape' ? PAGE.h : PAGE.w

  // ── Header band ──
  let x = MARGIN
  const logo = brand.logoUrl ? await loadImage(brand.logoUrl) : null
  if (logo) {
    const hMM = 12
    const wMM = Math.min(40, (logo.w / logo.h) * hMM)
    doc.addImage(logo.data, 'PNG', x, MARGIN - 2, wMM, hMM)
    x += wMM + 5
  }
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(20, 30, 40)
  doc.text(brand.title, x, MARGIN + 3.5)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(110, 125, 140)
  const dateLine = new Date().toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })
  doc.text(`${brand.companyName}${brand.subtitle ? ` · ${brand.subtitle}` : ''} · ${dateLine}`, x, MARGIN + 9)
  doc.setDrawColor(225, 230, 235)
  doc.setLineWidth(0.4)
  doc.line(MARGIN, MARGIN + 13, pw - MARGIN, MARGIN + 13)

  return {
    doc,
    pw,
    ph,
    /** y where page content starts, below the header. */
    contentTop: MARGIN + 17,
    /** Footer on every page, then save. Call LAST. */
    finish(filename: string) {
      const pages = doc.getNumberOfPages()
      for (let i = 1; i <= pages; i++) {
        doc.setPage(i)
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(7.5)
        doc.setTextColor(150, 160, 170)
        doc.text('Generated by HammerTrack · hammertrack.ai', MARGIN, ph - 6)
        doc.text(`Page ${i} of ${pages}`, pw - MARGIN, ph - 6, { align: 'right' })
      }
      doc.save(filename)
    },
  }
}

/** Capture a MapLibre canvas without preserveDrawingBuffer: snap inside a
 *  render callback so the frame buffer is still intact. */
export function captureMapCanvas(map: { getCanvas(): HTMLCanvasElement; once(ev: string, cb: () => void): unknown; triggerRepaint(): void }): Promise<string> {
  return new Promise((resolve, reject) => {
    try {
      map.once('render', () => {
        try { resolve(map.getCanvas().toDataURL('image/jpeg', 0.92)) } catch (e) { reject(e) }
      })
      map.triggerRepaint()
    } catch (e) {
      reject(e)
    }
  })
}
