-- 088: one-time heal of the usage_daily decay 087 fixed.
--
-- Before 087 the hourly rebuild deleted usage_daily for the first day of its
-- window and re-inserted only what the window's own pings produced, so every
-- day's ledger row lost the site visits that ended before the window's start
-- on that day (a truck leaving a site at 4 PM vanished from that day's hours
-- once the hourly window's start passed 4 PM). zone_sessions kept the visits,
-- so a from-scratch replay restores the exact per-day rows. 90 days back
-- covers every ping on record (pilot data starts Jul 6; ingest drops fixes
-- older than 30 days). Runs once, at deploy, with the 087 function: one
-- bounded pass per billing zone over the company's full history — the same
-- work one pre-087 hourly run did, done for the last time.
--
-- Separate file so the 087 fix commits even if this replay is interrupted;
-- a retry is just a new migration file with the same statement.
SELECT rebuild_all_usage(now() - INTERVAL '90 days', now());
